version: '3'

# Use for local machine
services:
  influxdb:
    image: influxdb:2.3-alpine
    container_name: binobs-influxdb
    volumes:
      - ../.volumes/influxdb:/var/lib/influxdb
      - ./influxdb:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=binobs
      - DOCKER_INFLUXDB_INIT_PASSWORD=binobs123
      - DOCKER_INFLUXDB_INIT_ORG=binobs
      - DOCKER_INFLUXDB_INIT_BUCKET=binobs
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=binobs-token
    networks:
      - metrics-network
    ports:
      - "8086:8086"
    tty: true

  grafana:
    image: grafana/grafana-oss:9.0.5
    container_name: binobs-grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../.volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - metrics-network
    tty: true

networks:
  metrics-network: {}